env:
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-undef: 0
  no-underscore-dangle: ["error", { "allow": ["__dirname", "__filename"] }]